apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dphw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dphw
    app.kubernetes.io/part-of: ci1t-830-0092-app
  name: devfile-sample-dphw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dphw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dphw
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0092-tenant/ci1t-830-0092-app/devfile-sample-dphw@sha256:f7d205a60676d910f70a33d0e1a17d7e1ff0394395239522ee2f0bc4ab9c37da
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
